BaseURL = "https://gophercoders.com"
languageCode = "en-GB"
title = "Gopher Coders"
theme = "littlegophers2"
MetaDataFormat = "toml"
[permalinks]
    post = "/:year/:month/:title/"
[Taxonomies]
    tag = "tags"
    keystage = "keystage"
    concept = "concepts"
    featured = "featured"
    category = "categories"
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
